// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {DeployFullStackBase} from "./DeployFullStackBase.s.sol";

/// @notice Full-stack deployment script for chains that already provide a public ERC-8004 identity registry.
///
/// Required env:
///   PRIVATE_KEY
///   EXTERNAL_IDENTITY_REGISTRY_ADDRESS
///
/// Strongly recommended in production:
///   STRICT_ROLE_CONFIGURATION=true
///   EVO_CORE_ADMIN_ADDRESS=0x...
///   AGENT_SIGNER_ADDRESS=0x...
///   PREDICTION_MANAGER_ADDRESS=0x...
///   PREDICTION_RESULT_PUBLISHER_ADDRESS=0x...
///   PREDICTION_SNAPSHOT_PUBLISHER_ADDRESS=0x...
///   COMMITTEE_ORACLE_ADMIN_ADDRESS=0x...
///   COMMITTEE_ORACLE_GOVERNOR_ADDRESS=0x...
///   COMMITTEE_ORACLE_TIMELOCK_EXECUTOR_ADDRESS=0x...
///   COMMITTEE_ORACLE_EMERGENCY_GUARDIAN_ADDRESS=0x...
///   COMMITTEE_ORACLE_AUTOMATION_ADDRESS=0x...
///   COMMITTEE_ORACLE_CHALLENGE_ADDRESS=0x...
///   COMMITTEE_ORACLE_JUROR_MANAGER_ADDRESS=0x...
///   COMMITTEE_ORACLE_JUROR_APPROVER_ADDRESS=0x...
contract DeployFullStackPublicIdentity is DeployFullStackBase {
    function _applyIdentityModeConfig(DeployConfig memory cfg) internal view override returns (DeployConfig memory) {
        cfg.identityRegistry = vm.envAddress("EXTERNAL_IDENTITY_REGISTRY_ADDRESS");
        cfg.strictRoleConfiguration = _envBoolOr("STRICT_ROLE_CONFIGURATION", true);
        return cfg;
    }
}
